version: 1.0.{build}
branches:
  only:
  - master
  - develop
  - feature_wall_functions
image: Visual Studio 2015
configuration: release
platform: x64
build_script:
- ps: >-
    powershell ci\\appveyor\\installMPI.ps1

    powershell ci\\appveyor\\buildAither.ps1
test_script:
- ps: powershell ci\\appveyor\\runRegressionTests.ps1