language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

osx_image: xcode8

branches:
  only:
    - master
    - develop

# setup build matrix
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5 gcc-5
      env:
        - CXX_COMPILER=g++-5
        - C_COMPILER=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 gcc-6
      env:
        - CXX_COMPILER=g++-6
        - C_COMPILER=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang++-3.8 clang-3.8 libc++-dev libc++abi-dev
      env:
        - CXX_COMPILER=clang++-3.8
        - C_COMPILER=clang-3.8
      
# upgrade packages
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc-5 gcc-6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX_COMPILER" == "clang++-3.8"]]; then CXX_COMPILER=clang++; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$C_COMPILER" == "clang-3.8"]]; then C_COMPILER=clang; fi
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

# install mpi
install:
  - bash travis/installMPI

# build instructions
script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DMPI_DIR=../openmpi -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=aither ..
  - make -j4
  - make install