language: cpp
sudo: required
dist: trusty

# setup build matrix
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5 gcc-5
      env:
        - CXX_COMPILER=g++-5
        - C_COMPILER=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 gcc-6
      env:
        - CXX_COMPILER=g++-6
        - C_COMPILER=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang++-3.8 clang-3.8 libc++-dev libc++abi-dev
      env:
        - CXX_COMPILER=clang++-3.8
        - C_COMPILER=clang-3.8
      
# get mpi installed from source
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - bash travis/installMPI

# build instructions
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DMPI_DIR=../openmpi -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=aither ..
  - make -j4
  - make install