# Site settings
title: Aither
baseurl: "/"
url: http://mnucci32.github.io/aither
twitter_username: aitherCFD
github_username: mnucci32

exclude: [aither, testCases]

# Build settings
markdown: kramdown
